<form class="navbar-form navbar-right" action="<?php echo $this->element->getAction(); ?>" method="post">
    <div class="form-group">
        <?php echo $this->element->logincsrf;?>
    </div>
    <div class="form-group">
        <!--<input type="text" placeholder="Email" class="form-control">-->
        <?php echo $this->element->username; ?>
    </div>
    <div class="form-group">
        <!--<input>-->
        <?php echo $this->element->password;?>
    </div>
    <button type="submit" class="btn btn-success">Sign In</button>
</form>